use strict;
use warnings;
use Test::More;
use File::Temp qw(tempfile);
use lib 'lib';
use PVE::DC::PowerSave::Config;

my ($fh, $path) = tempfile();
close($fh);
my $cfg = PVE::DC::PowerSave::Config->defaults;
my $digest = PVE::DC::PowerSave::Config->digest($path);
my $saved = PVE::DC::PowerSave::Config->save($cfg, $path, $digest);
is(PVE::DC::PowerSave::Config->load($path)->{enabled}, 0, 'configuration starts disabled');
is($saved, PVE::DC::PowerSave::Config->digest($path), 'digest follows write');
open(my $reader, '<', $path) or die "cannot open $path: $!";
my $before = do { local $/ = undef; my $raw = <$reader>; seek($reader, 0, 0); $raw };
$saved = PVE::DC::PowerSave::Config->save({ %$cfg, enabled => 1 }, $path, $saved);
my $seen = do { local $/ = undef; <$reader> };
close($reader);
is($seen, $before, 'save replaces the file instead of truncating it under concurrent readers');
is(PVE::DC::PowerSave::Config->load($path)->{enabled}, 1, 'replacement content is visible to new readers');
my $dir = $path; $dir =~ s|/[^/]+$||;
opendir(my $dh, $dir) or die "cannot list $dir: $!";
my ($base) = $path =~ m|([^/]+)$|;
is_deeply([grep { /^\Q$base\E\.tmp\./ } readdir($dh)], [], 'no temporary file is left behind');
closedir($dh);
eval { PVE::DC::PowerSave::Config->save({ %$cfg, enabled => 1 }, $path, $digest) };
like($@, qr/configuration changed/, 'stale UI write is rejected');
eval { PVE::DC::PowerSave::Config->parse("enabled: 1\nunknown_key: 1\n") };
like($@, qr/unknown setting/, 'unknown setting cannot silently change policy');
eval { PVE::DC::PowerSave::Config->parse("idle_governor: powersave;touch /tmp/x\n") };
like($@, qr/invalid idle_governor/, 'governor cannot contain shell syntax');
unlink($path);
done_testing;
